export default {
  login: 'Skydiver412',
  id: 57918922,
  node_id: 'MDQ6VXNlcjU3OTE4OTIy',
  avatar_url: 'https://avatars.githubusercontent.com/u/57918922?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Skydiver412',
  html_url: 'https://github.com/Skydiver412',
  followers_url: 'https://api.github.com/users/Skydiver412/followers',
  following_url:
    'https://api.github.com/users/Skydiver412/following{/other_user}',
  gists_url: 'https://api.github.com/users/Skydiver412/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/Skydiver412/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Skydiver412/subscriptions',
  organizations_url: 'https://api.github.com/users/Skydiver412/orgs',
  repos_url: 'https://api.github.com/users/Skydiver412/repos',
  events_url: 'https://api.github.com/users/Skydiver412/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Skydiver412/received_events',
  type: 'User',
  site_admin: false,
  name: 'Brian Kunkel',
  company: 'Sienna Mercato',
  blog: '',
  location: 'Pittsburgh',
  email: null,
  hireable: null,
  bio: 'Chef, Skydiver, and web/game development enthusiast.',
  twitter_username: 'SkyDesigner412',
  public_repos: 0,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2019-11-18T20:03:18Z',
  updated_at: '2021-11-02T23:57:02Z',
};
